common_settings: &common_settings
  consul:
    uri: http://localhost:8500/v1
    ttl: 180                    # seconds
  nosql:
    table_prefix: guest-development-
  s3:
    bucket: 'healthtap-guest'
    hostname: 's3.amazonaws.com'

development:
  <<: *common_settings

qa:
  <<: *common_settings

test:
  <<: *common_settings

production:
  <<: *common_settings
  nosql:
    table_prefix: guest-production-l
