common_settings: &common_settings
  consul:
    uri: http://127.0.0.1:8500/v1
    ttl: 180                    # seconds
  nosql:
    table_prefix: guest-development-

development:
  <<: *common_settings

test:
  <<: *common_settings
  
production:
  <<: *common_settings
